plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vid.tvcloser2'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vid.tvcloser2'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '3.0-AutoActivate'

        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.11.0'
}
